#vim: set ft=ansible:
---
- name: Step 000 post software dummy
  hosts: localhost
  connection: local
  become: false
  vars_files:
    - "./env_vars.yml"
    - "./env_secret_vars.yml"
  tags:
    - step005
  tasks:
    - debug:
        msg: "Step 000 post software - Dummy action"

- name: Configure Provisioner for CF integration
  hosts: "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_provisioner') | replace('-', '_') }}"
  become: yes
  gather_facts: False
  vars:
    symlinks:
      - src: /opt/OPEN_Admin/OPENTLC-OCP3/provision_workshop_env.sh
        path: /home/opentlc-mgr/bin/provision_workshop_env.sh
      - src: /opt/OPEN_Admin/OPENTLC-OCP3/provision-ose-projects.sh
        path: /home/opentlc-mgr/bin/provision-ose-projects.sh
      - src: /opt/OPEN_Admin/OPENTLC-OCP3/deploy_scripts
        path: /home/opentlc-mgr/bin/deploy_scripts
  roles:
    - role: "{{ ANSIBLE_REPO_PATH }}/roles/opentlc-integration"
      when: install_opentlc_integration == true
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  tags: [ env-specific, cf_integration ]
  tasks:
    - name: Copy ssh key to provisioner
      copy:
        src: "~/.ssh/{{ key_name }}.pem"
        dest: "/home/opentlc-mgr/.ssh/{{ key_name }}.pem"

    - name: Install EPEL (for jq)
      package:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        use: yum
        state: installed

    - name: install python-pip
      yum:
        name: python2-pip

    - name: Install awscli
      pip:
        name: awscli

    - name: test awscli
      command: aws --version

    - name: create ~opentlc-mgr/.aws 
      file:
        path: /home/opentlc-mgr/.aws
        owner: opentlc-mgr
        group: opentlc-mgr
        state: directory

    - name: Insert awscli credentials
      copy:
        dest: /home/opentlc-mgr/.aws/credentials
        owner: opentlc-mgr
        group: opentlc-mgr
        content: |
          [default]
          aws_access_key_id = {{aws_access_key_id}}
          aws_secret_access_key = {{aws_secret_access_key}}

    - name: Copy boto.cfg file to /etc
      copy:
        src: "{{ ANSIBLE_REPO_PATH }}/inventory/boto.cfg"
        dest: /etc/boto.cfg

    - name: Copy Sync_Repositories.sh file to /root
      copy:
        src: "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/files/Sync_Repositories.sh"
        dest: /root/

    - name: install lvm2
      yum:
        name: lvm2
    
    - lvg:
        vg: "{{ storage_vg }}"
        pvs: "{{ storage_pvs }}"
      ignore_errors: true

    - lvol:
        vg: "{{ storage_vg }}"
        lv: storagelv
        size: 100%FREE
      ignore_errors: true

    - filesystem:
        fstype: ext4
        dev: "/dev/{{ storage_vg }}/storagelv"
      ignore_errors: true

    - file:
        path: "{{ storage_mount_path }}"
        state: directory
        mode: 0777

    - selinux:
        policy: targeted
        state: permissive

    - lineinfile:
        dest: /etc/fstab
        insertafter: EOF
        line: "/dev/{{ storage_vg }}/storagelv {{ storage_mount_path}} ext4 defaults 0 0"
        state: present
      ignore_errors: true

    - shell: "mkdir -p {{ storage_mount_path }} &&  mount {{ storage_mount_path }}"
      ignore_errors: true
#    - shell: "SELINUX=enforcing"
    #- shell: "systemctl enable http && systemctl restart httpd"
    #- shell: "ln -s {{storage_mount_path}}/repos /var/www/html/repos"
#    - shell: "chcon -R -t httpd_user_content_t /srv"
#    - shell: "chcon -R -t httpd_user_content_t /var/www/html/repos"
### Still need to add "env_secret_vars" files to actually get this to work
### still need to run the repository sync script.
