#vim: set ft=ansible:
---
# tasks file for bastion

######################### Setting up environment for post deployment administration
- name: copy the environment .pem key
  become: true
  copy:
    src: "{{ ANSIBLE_REPO_PATH }}/workdir/{{ env_authorized_key }}"
    dest: "~{{ item }}/.ssh/{{env_authorized_key}}.pem"
    owner: "{{ item }}"
    mode: 0400
  with_items:
    - root
    - "{{ remote_user }}"
  when: use_own_key|bool

- name: copy the user's SSH private key
  become: true
  copy:
    src: "~/.ssh/{{key_name}}.pem"
    dest: "~{{ item }}/.ssh/{{key_name}}.pem"
    owner: "{{ item }}"
    mode: 0400
  with_items:
    - root
    - "{{ remote_user }}"
  when: not use_own_key|bool
  tags:
    - copy_env_private_key

# TODO: Test splitting this into literal
- name: Generate host .ssh/config Template
  become: no
  local_action: template src={{ role_path }}/files/bastion_ssh_config.j2 dest={{ ANSIBLE_REPO_PATH }}/workdir/ssh-config-{{ env_type }}-{{ guid }}
  when: not use_own_key|bool
  tags:
    - gen_sshconfig_file

- name: Generate host .ssh/config Template
  become: no
  local_action: template src={{ role_path }}/files/bastion_ssh_config_ownkey.j2 dest={{ ANSIBLE_REPO_PATH }}/workdir/ssh-config-{{ env_type }}-{{ guid }}
  when: use_own_key|bool
  tags:
    - gen_sshconfig_file

- name: copy over host .ssh/config Template
  become: true
  copy:
    src: "{{ ANSIBLE_REPO_PATH }}/workdir/ssh-config-{{ env_type }}-{{ guid }}"
    dest: "~{{ item }}/.ssh/config"
    owner: "{{ item }}"
    mode: 0400
  with_items:
    - root
    - "{{ remote_user }}"
  tags:
    - copy_sshconfig_file
