#vim: set ft=ansible:
---
# tasks file for bastion

######################### Setting up environment for post deployment administration

- name: install ipa client packages
  yum:
    name: "ipa-client"
    state: present

- name: Register bastion with IPA
  shell: "/usr/sbin/ipa-client-install --domain=OPENTLC.COM -w {{ipa_host_password}} -N -U --mkhomedir --no-dns-sshfp --hostname={{bastion_public_dns_chomped}}"

# quick fix for sssd
- name: check IPA authorized_key
  command: /usr/bin/sss_ssh_authorizedkeys jenkins-sfo01
  register: output_sss
  changed_when: false
  ignore_errors: true

- name: restart until IPA is working
  until: output_sss | succeeded
  retries: 10
  delay: 20
  block:
  - name: Restart sssd
    service:
      name: sssd
      state: restarted

  - name: check IPA authorized_key
    command: /usr/bin/sss_ssh_authorizedkeys jenkins-sfo01
    register: output_sss
    changed_when: false
    ignore_errors: true

- name: Add opentlc-access ipa group to sudoers.d
  lineinfile:
    path: /etc/sudoers.d/opentlc-sudoers
    state: present
    create: yes
    line: '%opentlc-access ALL=(ALL)       NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'


- name: copy over ipa_optimize.sh script
  copy:
    src: "{{ role_path }}/files/ipa_optimize.sh"
    dest: /opt/ipa_optimize.sh
    owner: root
    group: root
    mode: 0700
  notify: Run ipa_optimize.sh
