# vim: set ft=ansible:
---
- name: Add opentlc-mgr user
  user:
    name: opentlc-mgr
    home: /home/opentlc-mgr

- name: Install git
  yum:
    name: git

- name: Get updated files from git repository github.com/sborenst/ansible_agnostic_deployer
  git:
    repo: "https://github.com/sborenst/ansible_agnostic_deployer.git"
    dest: /home/opentlc-mgr/ansible_agnostic_deployer
    force: yes

- name: Check if OPEN_Admin.tar.gz repo exists in the current dir (manual upload)
  delegate_to: localhost
  stat:
    path: "{{ ANSIBLE_REPO_PATH }}/OPEN_Admin.tar.gz"
  register: openadmin_archive

- name: Check if file exists remotely.
  stat:
    path: /home/opentlc-mgr/OPEN_Admin
  register: remote_openadmin

- name: Copy and unarchive OPEN_Admin.tar.gz repo from local. Do not copy if already present remotely.
  unarchive:
    src: "{{ ANSIBLE_REPO_PATH }}/OPEN_Admin.tar.gz"
    dest: /home/opentlc-mgr/
  when:
    - openadmin_archive.stat.exists
    - not remote_openadmin.stat.exists

- name: Get updated files from git repository github.com/redhat-gpe/OPEN_Admin.git
  git:
    repo: "https://{{ githubuser }}:{{ githubpassword }}@github.com/redhat-gpe/OPEN_Admin.git"
    dest: /home/opentlc-mgr/OPEN_Admin
    force: yes
  when:
    - githubuser is defined
    - githubpassword is defined
    - not openadmin_archive.stat.exists

- name: Set permissions for directories OPEN_Admin and ansible_agnostic_deployer
  file:
    path: "/home/opentlc-mgr/{{ item }}"
    state: directory
    owner: opentlc-mgr
    recurse: yes
    group: opentlc-mgr
    mode: 0770
  with_items:
    - OPEN_Admin
    - ansible_agnostic_deployer

- name: Create ~opentlc-mgr/bin
  file:
    path: /home/opentlc-mgr/bin
    state: directory

# these symlinks are usually specific (bastion, ansible-provisionner, etc)
- name: Create symlinks to ~opentlc-mgr/bin
  file:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    state: link
  with_items: "{{ symlinks }}"

- name: add CF key
  authorized_key:
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4OojwKH74UWVOY92y87Tb/b56CMJoWbz2gyEYsr3geOc2z/n1pXMwPfiC2KT7rALZFHofc+x6vfUi6px5uTm06jXa78S7UB3MX56U3RUd8XF3svkpDzql1gLRbPIgL1h0C7sWHfr0K2LG479i0nPt/X+tjfsAmT3nWj5PVMqSLFfKrOs6B7dzsqAcQPInYIM+Pqm/pXk+Tjc7cfExur2oMdzx1DnF9mJaj1XTnMsR81h5ciR2ogXUuns0r6+HmsHzdr1I1sDUtd/sEVu3STXUPR8oDbXBsb41O5ek6E9iacBJ327G3/1SWwuLoJsjZM0ize+iq3HpT1NqtOW6YBLR opentlc-mgr@inf00-mwl.opentlc.com
    user: opentlc-mgr

- file:
    path: /home/opentlc-mgr/deployer_logs
    state: directory
    owner: opentlc-mgr
    recurse: yes
