# vim: set ft=ansible:
---
- name: Add opentlc-mgr user
  user:
    name: opentlc-mgr
    home: /home/opentlc-mgr

- name: install git
  yum:
    name: git

- name: Get updated files from git repository github.com/sborenst/ansible_agnostic_deployer
  git:
    repo: "https://{{ githubuser }}:{{ githubpassword }}@github.com/sborenst/ansible_agnostic_deployer.git"
    dest: /opt/ansible_agnostic_deployer
    force: yes

- name: Get updated files from git repository github.com/redhat-gpe/OPEN_Admin.git
  git:
    repo: "https://{{ githubuser }}:{{ githubpassword }}@github.com/redhat-gpe/OPEN_Admin.git"
    dest: /opt/OPEN_Admin
    force: yes

- name: Set permissions for directories OPEN_Admin and ansible_agnostic_deployer
  file:
    path: "/opt/{{ item }}"
    state: directory
    owner: opentlc-mgr
    recurse: yes
    group: opentlc-mgr
    mode: 0770
  with_items:
    - OPEN_Admin
    - ansible_agnostic_deployer

- name: Create ~opentlc-mgr/bin
  file:
    path: /home/opentlc-mgr/bin
    state: directory

# these symlinks are usually specific (bastion, ansible-provisionner, etc)
- name: Create symlinks to ~opentlc-mgr/bin
  file:
    path: "/home/opentlc-mgr/bin/{{ item }}"
    src: "/opt/OPEN_Admin/OPENTLC-OCP3/{{ item }}"
    state: link
  with_items: "{{ symlinks }}"

- name: add CF key
  authorized_key:
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4OojwKH74UWVOY92y87Tb/b56CMJoWbz2gyEYsr3geOc2z/n1pXMwPfiC2KT7rALZFHofc+x6vfUi6px5uTm06jXa78S7UB3MX56U3RUd8XF3svkpDzql1gLRbPIgL1h0C7sWHfr0K2LG479i0nPt/X+tjfsAmT3nWj5PVMqSLFfKrOs6B7dzsqAcQPInYIM+Pqm/pXk+Tjc7cfExur2oMdzx1DnF9mJaj1XTnMsR81h5ciR2ogXUuns0r6+HmsHzdr1I1sDUtd/sEVu3STXUPR8oDbXBsb41O5ek6E9iacBJ327G3/1SWwuLoJsjZM0ize+iq3HpT1NqtOW6YBLR opentlc-mgr@inf00-mwl.opentlc.com
    user: opentlc-mgr

- file:
    path: /opt/deployer_logs
    state: directory
    owner: opentlc-mgr
    recurse: yes
