---
- name: test that command worked
  debug:
    var: ocp_user_groups

- name: Remove user from developer group (remove ability to create projects)
  shell: "oadm groups remove-users {{item}} {{ocp_username}}"
  register: groupadd_register
  with_items: "{{ocp_user_groups}}"
  when: username is defined and ocp_user_groups is defined

- name: test that command worked
  debug:
    var: groupadd_register
    verbosity: 2

- name: Remove user Quota - clusterresourcequota
  shell: oc delete clusterresourcequota clusterquota-{{ocp_username}}-{{guid}}
