---
- name: define ocp_project
  set_fact:
    ocp_project: "enmasse-{{guid}}"

- name: Create project for workload
  shell: "oc new-project {{ocp_project}}"

- name: Make sure we go back do default project
  shell: "oc project default"

- name: Create service account for address controller
  shell: "oc create sa enmasse-admin -n $NAMESPACE"

- name: Add permissions for viewing OpenShift resources to default user
  shell: "oc policy add-role-to-user view system:serviceaccount:{{ocp_project}}:default"

- name:
  shell: "oc policy add-role-to-user edit system:serviceaccount:{{ocp_project}}:enmasse-admin"

- name: Add permissions for editing OpenShift resources to admin SA
  shell: "oc policy add-role-to-user edit system:serviceaccount:{{ocp_project}}:enmasse-admin"

- name: Create none authservice
  shell: "oc process -f $NONE_TEMPLATE | oc create -n $NAMESPACE -f -"

- name: Instantiate EnMasse template
  shell: "oc process -f $ENMASSE_TEMPLATE $TEMPLATE_PARAMS | oc create -n $NAMESPACE -f -"


#create_self_signed_cert "oc" "address-controller.{{ocp_project}}.svc.cluster.local" "address-controller-cert"
#create_self_signed_cert "oc" "none-authservice.{{ocp_project}}.svc.cluster.local" "none-authservice-cert"

- name: Create serviceaccount-as-oauthclient
  shell: "oc create -f https://raw.githubusercontent.com/syndesisio/syndesis/master/app/deploy/support/serviceaccount-as-oauthclient-restricted.yml -n {{ocp_project}}
"

- name: Create workload template
  shell: "oc create -f https://raw.githubusercontent.com/syndesisio/syndesis/master/app/deploy/syndesis-restricted.yml -n {{ocp_project}}
"

- name: Create the workload app
  shell: |
      oc new-app syndesis-restricted -p ROUTE_HOSTNAME=fuse.{{ocp_project}}.{{ocp_apps_domain}} \
      -p OPENSHIFT_PROJECT={{ocp_project}} \
      -p OPENSHIFT_OAUTH_CLIENT_SECRET=$(oc sa get-token syndesis-oauth-client -n {{ocp_project}}) -n {{ocp_project}}

- name: Give ocp_username access to ocp_project
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{ocp_project}}"

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
